export const ROUTES = Object.freeze({
  TRAINING: "TRAINING",
  TRAINING_SESSION: "TRAINING_SESSION",
  CALENDAR: "CALENDAR",
  JOURNAL: "JOURNAL",
  SQUAD: "SQUAD",
  SHOP: "SHOP",
  PROFILE: "PROFILE",
});

export const DEFAULT_ROUTE = ROUTES.TRAINING;
